// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface About {
  id: string;
  slug: string | null;
  status: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Contact {
  id: string;
  slug: string | null;
  status: string;
  platform?: string;
  url?: string;
  display_label?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Experience {
  id: string;
  slug: string | null;
  status: string;
  company?: string;
  role?: string;
  start_date?: string;
  end_date?: string;
  description?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Profile {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  title?: string;
  intro?: PortableTextBlock[];
  resume_url?: string;
  avatar_url?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Project {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: string;
  featured_image_alt?: string;
  client?: string;
  year?: string;
  summary?: string;
  content?: PortableTextBlock[];
  gallery?: unknown;
  url?: string;
  live_url?: string;
  tag?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Skill {
  id: string;
  slug: string | null;
  status: string;
  name?: string;
  category?: string;
  level?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    abouts: About;
    contacts: Contact;
    experiences: Experience;
    profiles: Profile;
    projects: Project;
    skills: Skill;
  }
}